version: '3.7'

volumes:
  logs:
    driver: local

services:
  mail-validator-service:
    image: php:7-alpine
    working_dir: /var/www
    command: php -S localhost:8001 app.php
    environment:
      docker: "true"
    ports:
      - 8001:8001
    volumes:
      - .:/var/www
      - logs:/var/www/logs