<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer
{
    const METHOD_MAPPING = array(
  'MailValidator\\Validator\\Service\\Validator' => 'get1',
);

    protected function get1()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
            return (new \MailValidator\Validator\Service\Validator())
                    ->addValidator((new \MailValidator\Validator\Regex()))
                    ->addValidator((new \MailValidator\Validator\Domain()))
                    ->addValidator((new \MailValidator\Validator\Smtp()));
        }, 'MailValidator\\Validator\\Service\\Validator');
    }
}
